#!/bin/bash

    bin/okex-market-maker-keeper \
        --okex-api-server https://www.okex.com \
        --okex-api-key c0160a75-5546-41ac-9907-04f2b0c26bb3 \
        --okex-secret-key 2FBBA27BD1CA7C671C8B679C86EDAB00 \
        --okex-password hkmaker12345 \
        --okex-timeout 9.5 \
        --pair DAI_USDT \
        --config ./bands.json \
        --price-feed ok_dai_usdt
